version: "3.9"

services:
  database:
    image: postgres
    container_name: delivery_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=delivery-api
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local